name: CI

on:
  push:
    tags:
      - "*"
    paths:
      - Package Managers.alfredworkflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          title: ${{ github.ref }}

      - name: GitHub Upload Release Artifacts
        uses: Shopify/upload-to-release@v2.0.0
        with:
          name: Package.Managers.alfredworkflow
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          path: Package Managers.alfredworkflow
